### ISSUE TITLE
dependency update needed on package monad-control

### ISSUE THREAD

**Issue by drhodes** [norm2782/snaplet-hdbc#11]
using the updated packages in hackage, I'm having a bit of trouble building.
on: x86 linux,  ghc 7.0.4, with haskell platform: 2011.4.0.0

--8<------------------------
snaplet-hdbc $ cabal configure
Resolving dependencies...
Configuring snaplet-hdbc-0.7...
cabal: At least the following dependencies are missing:
monad-control ==0.2.*
--8<------------------------

So I bumped the version

in file:    snaplet-hdbc / snaplet-hdbc.cabal, from .3 to 0.3.2 

...
monad-control             >= 0.2     && < 0.3.2,
...

leads to a successful configure, however fails to build with error
--8<------------------------
Preprocessing library snaplet-hdbc-0.7...
Building snaplet-hdbc-0.7...

src/Snap/Snaplet/Hdbc.hs:81:19:
    Could not find module `Control.Monad.IO.Control':
--8<------------------------

So maybe the API for monad-control changed?

**Comment by norm2782** [comment]
The monad-control API changed quite a bit in the new release. I've committed a patch to make the snaplet work with both monad-control-0.2.x and monad-control-0.3.x (3db7b8c12d260519cc82924f24882c64c20ffd9d). I have also uploaded a new version of the snaplet to hackage. It does require testing, though.
